### ISSUE TITLE
Interpolation key 'simulation.fire_start_seed' not found

### ISSUE THREAD

**Issue by Nebreg3** [mitrefireline/simharness#4]
**Issue**
When running the main.py of simharness, after installing all the dependencies, initializing the ray cluster, and following the installation process, I encounter this error:

```
File "/home/userlinux/Documents/simharness-dev/main.py", line 176, in _instantiate_config
    env_settings = instantiate(cfg.environment, _convert_="partial")

raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'simulation.fire_start_seed' not found
```

Althougt in nfs/lslab2/fireline/simharness/experiments/2024-04-18_18-39-00/hydra_output/config.yaml i have:

```
random:
     seed: ${simulation.fire_start_seed}
```

**Temporaly solution:**
Comment out line 79 and 80 in both [conf/simulation/train/default.yaml](https://github.com/mitrefireline/simharness/blob/2c7be127cb6be164d1cb2afd9c8435c873e425b8/conf/simulation/train/default.yaml#L79) and [conf/simulation/eval/default.yaml](https://github.com/mitrefireline/simharness/blob/2c7be127cb6be164d1cb2afd9c8435c873e425b8/conf/simulation/eval/default.yaml#L79)

**Comment by afennelly-mitre** [comment]
This issue has been resolved with the updates in commit https://github.com/mitrefireline/simharness/commit/706d74cc47b30add70f0f3948be4f9df47e69de0.

@Nestor-UVE you should be able to launch a training experiment with the following command:

```bash
python main.py -cn train cli.data_dir=$HOME/.simharness
```

Please create a new issue if you are still having trouble running experiments with `main.py` on the `dev` branch. Thank you!
